//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAroundRussia.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Tours = new HashSet<Tour>();
        }
    
        public int IDEmployee { get; set; }
        public string SurnameEmployee { get; set; }
        public string NameEmployee { get; set; }
        public string MiddleNameEmployee { get; set; }
        public string PhoneNumberEmployee { get; set; }
        public string EmailEmployee { get; set; }
        public string LoginEmployee { get; set; }
        public string PasswordEmployee { get; set; }
        public Nullable<int> IDRole { get; set; }
    
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tour> Tours { get; set; }
    }
}
