//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAroundRussia.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;
    using System.Windows.Navigation;

    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.HotelOfTours = new HashSet<HotelOfTour>();
            this.TypeOfTours = new HashSet<TypeOfTour>();
        }
    
        public int IDTour { get; set; }
        public Nullable<int> TicketCountTour { get; set; }
        public string CountTicket
        {
            get
            {
                return "Билетов: " + Convert.ToString(this.TicketCountTour);
            }
        }
        public string NameTour { get; set; }
        public string DescriptionTour { get; set; }
        public Nullable<double> PriceTour { get; set; }
        public string FullPriceView
        {
            get
            {
                return Convert.ToString(this.PriceTour) + " РУБ.";
            }
        }
        public Nullable<bool> IsActual { get; set; }
        public string State
        {
            get
            {
                if((bool)this.IsActual)
                {
                    return "Актуален";
                }
                else
                {
                    return "Не актуален";
                }
            }
        }
        public SolidColorBrush colorBrush
        {
            get
            {
                if ((bool)this.IsActual)
                {
                    return Brushes.Green;
                }
                else
                {
                    return Brushes.Red;
                }
            }
        }
        public Nullable<int> IDEmployee { get; set; }
        public Nullable<int> IDClient { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelOfTour> HotelOfTours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypeOfTour> TypeOfTours { get; set; }
    }
}
